// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

type Feed struct {
	ID          int64
	Title       interface{}
	Description interface{}
	Link        interface{}
	FeedLink    interface{}
	Updated     interface{}
}
