// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package query

import (
	"context"
)

const getFeed = `-- name: GetFeed :one
SELECT id, title, description, link, feed_link, updated, updated_parsed, image_id, guid FROM feed
WHERE id = ? LIMIT 1
`

func (q *Queries) GetFeed(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Link,
		&i.FeedLink,
		&i.Updated,
		&i.UpdatedParsed,
		&i.ImageID,
		&i.Guid,
	)
	return i, err
}
